default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.database_username %>
  password: <%= Rails.application.credentials.database_password %>
  host: localhost

development:
  <<: *default
  database: truebg_development

test:
  <<: *default
  database: truebg_test

production:
  <<: *default
  database: truebg_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>