default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:


development:
  <<: *default
  database: truebg_development

test:
  <<: *default
  database: truebg_test

production:
  <<: *default
  database: truebg_production
